config/routes.rb
Rails.application.routes.draw do
  
  authenticated :user do
    root to: "tweets#index", as: :authenticated_root
  end
  unauthenticated do
    root to: "main#index"
  end
  devise_for :users
  resources :users, only: [:index]
  devise_scope :user do
    post "/users/pre_register", to: "registrations#preRegister", as: :pre_registration
  end
  
  resources :tweets
  resources :conversations do
    resources :personal_messages, only: [:create]
  end
  
  put "/tweets/:id/like", to: "tweets#like", as: :like_tweet
  put "/tweets/:id/dislike", to: "tweets#dislike", as: :dislike_tweet
  
  get "/tweets/:parent_id/reply", to: "tweets#new", as: :reply_tweet
  get "/tweets/:parent_id/reply", to: "tweets#create"
  get "/tweets/:src_tweet/retweet", to: "tweets#new", as: :new_retweet
  post "/tweets/:src_tweet/retweet", to: "tweets#retweet", as: :retweet
  delete "/tweets/:id/retweet", to: "tweets#destroy_retweet", as: :destroy_retweet 
  post '/users/:username/follow_user', to: "relationships#follow_user", as: :follow_user
  post '/users/:username/unfollow_user', to: "relationships#unfollow_user", as: :unfollow_user
  
  get "/notifications", to: "notifications#index", as: :notification

  get "/search", to: "main#search", as: :search

  mount ActionCable.server => "/cable"

  get "/users/:username", to: "profiles#show", as: :profile_user, constraint: { username: /[\w]+/ }
  get "/users/:username/following", to: "profiles#following", as: :user_following, constraint: { username: /[\w]+/ }
  get "/users/:username/followers", to: "profiles#followers", as: :user_followers, constraint: { username: /[\w]+/ }

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_user, except: [:index]
	before_action :set_notifications_count, except: [:index]

	def index
		@users = User.all
	end

	def show
		@tweets = @user.tweets.order("created_at DESC")
		@notifications_count = notifications_count
		# respond_to do |format|
		# 	format.html
		# 	format.js
		# end
	end

	def following
		@following = @user.following.order("created_at DESC")

	end

	def followers
		@followers = @user.followers.order("created_at DESC")
	end

	private
		def set_user
			@user = User.find_by(username: params[:username]) || not_found
		end

		def set_notifications_count
			@notifications_count = notifications_count
		end

end

app/views/profiles/_profile_header.html.haml
.profile-bg
	= image_tag user.cover, class: "img-responsive"
.bar
	.container
		.profile-avatar.thumbnail
			= image_tag user.avatar
		.profile-card
			= link_to profile_user_path(user.username) do
				.fullname
					%span
						%strong= user.name
				%small.username
					@#{user.username}
			- unless current_page?(root_path)
				.bio
					%p= user.bio
		.profile-nav
			- if current_page?(root_path) || user.username == params[:username]
				%ul.nav.nav-tabs
				
					%li.nav-items
						= link_to profile_user_path(user.username), class: "nav-link active", id: "nav-tweets", remote: true do 
							%span.tab-value= user.tweets.size
							%span.tab-label Tweets
					%li.nav-items
						= link_to user_following_path(user.username), class: "nav-link", id: "nav-following", remote: true do
							%span.tab-value= user.following.size
							%span.tab-label Following
					%li.nav-items
						= link_to user_followers_path(user.username), class: "nav-link", id: "nav-followers", remote: true do
							%span.tab-value= user.followers.size
							%span.tab-label Followers
			- unless current_page?(root_path) #|| current_page?( search_path) 
				- if current_user == user
					= link_to edit_user_registration_path, class: "btn btn-default btn-edit" do
						%i.fa.fa-edit
						%span Edit profile
				- else
					- if current_user_is_following(current_user.id, user.id)
						= link_to unfollow_user_path(user.username), class: "btn btn-default btn-unfollow", method: :post, remote: true do
							%i.fa.fa-check
							%i.fa.fa-user-times
							%span Following
					- else
						= link_to follow_user_path(user.username), class: "btn btn-default btn-follow", method: :post, remote: true do
							%i.fa.fa-user-plus
							%span Follow
					  

app/views/profiles/followers.js.erb
$(".users").html("<%= j render @followers %>");
$(".users").removeClass("hidden");
$(".profile-tweets").html("");
$(".profile-tweets").addClass("hidden");
$("#nav-followers").addClass("active");
$("#nav-following").removeClass("active");
$("#nav-tweets").removeClass("active");

app/views/profiles/following.js.erb
$(".users").html("<%= j render @following %>");
$(".users").removeClass("hidden");
$(".profile-tweets").html("");
$(".profile-tweets").addClass("hidden");
$("#nav-following").addClass("active");
$("#nav-followers").removeClass("active");
$("#nav-tweets").removeClass("active");

app/views/profiles/show.html.haml
.profile-page
	.profile-header
		= render "profile_header", user: @user
	.container
		.row
			.profile-sidebar.col-sm-3.col-md-2
				.profile-card
					= link_to profile_user_path(@user) do
						.fullname
							%span= @user.name
						.username
							%span @#{ @user.username }
					.bio
						= @user.bio
					.info
						.created_at
							%i.fa.fa-calendar
							%span= @user.created_at.to_date
			.profile-tweets.col-sm-7.col-md-6.col-sm-offset-1
				= render @tweets

			.users.col-sm-8.col-md-9.col-sm-offset-1.hidden
				- if @following
					= render @following
				- elsif @followers
					= render @followers

app/views/profiles/show.js.erb
$(".profile-tweets").html("<%= j render @tweets %>");
$(".users").addClass("hidden");
$(".users").html("");
$(".profile-tweets").removeClass("hidden");
$("#nav-tweets").toggleClass("active");
$("#nav-followers").toggleClass("active");
$("#nav-following").removeClass("active");