config/routes.rb
Rails.application.routes.draw do
  
  authenticated :user do
    root to: "tweets#index", as: :authenticated_root
  end
  unauthenticated do
    root to: "main#index"
  end
  devise_for :users
  resources :users, only: [:index]
  devise_scope :user do
    post "/users/pre_register", to: "registrations#preRegister", as: :pre_registration
  end
  
  resources :tweets
  resources :conversations do
    resources :personal_messages, only: [:create]
  end
  
  put "/tweets/:id/like", to: "tweets#like", as: :like_tweet
  put "/tweets/:id/dislike", to: "tweets#dislike", as: :dislike_tweet
  
  get "/tweets/:parent_id/reply", to: "tweets#new", as: :reply_tweet
  get "/tweets/:parent_id/reply", to: "tweets#create"
  get "/tweets/:src_tweet/retweet", to: "tweets#new", as: :new_retweet
  post "/tweets/:src_tweet/retweet", to: "tweets#retweet", as: :retweet
  delete "/tweets/:id/retweet", to: "tweets#destroy_retweet", as: :destroy_retweet 
  post '/users/:username/follow_user', to: "relationships#follow_user", as: :follow_user
  post '/users/:username/unfollow_user', to: "relationships#unfollow_user", as: :unfollow_user
  
  get "/notifications", to: "notifications#index", as: :notification

  get "/search", to: "main#search", as: :search

  mount ActionCable.server => "/cable"

  get "/users/:username", to: "profiles#show", as: :profile_user, constraint: { username: /[\w]+/ }
  get "/users/:username/following", to: "profiles#following", as: :user_following, constraint: { username: /[\w]+/ }
  get "/users/:username/followers", to: "profiles#followers", as: :user_followers, constraint: { username: /[\w]+/ }

end

app/models/conversation.rb
class Conversation < ApplicationRecord
    # after_save { |conversation| conversation.destroy if conversation.personal_messages.empty? }
    belongs_to :author, class_name: "User"
    belongs_to :receiver, class_name: "User"
    has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy
    scope :participates, -> (user) { where(author: user).or(where(receiver: user)) }
    scope :between, -> (author, receiver) { where(author: author, receiver: receiver).or(where(author: receiver, receiver: author)) }

    def opposed_user(user)
        user == author ? receiver : author
    end

    def participates?(user)
        author == user || receiver == user
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_if_exists, only: [:create]
    before_action :set_conversation, only: [:show, :destroy]
    #after_action :destroy_if_empty, only: [:show]

    def index
        @conversations = Conversation.participates(current_user).order(updated_at: "DESC")
        respond_to do |format|
            format.html
            format.js
        end
    end

    def new
        @conversation = Conversation.new
        respond_to do |format|
            format.html
            format.js
        end
    end

    def create
        
        @conversation = current_user.authored_conversations.build(conversation_params)
        if @conversation.save
            respond_to do |format|
                format.js
            end
        end
    end

    def show
        @personal_message = PersonalMessage.new
        mark_as_read(@conversation.personal_messages.unread(current_user))
        respond_to do |format|
            format.html
            format.js
        end
    end

    def destroy
        if @conversation.destroy
            redirect_to conversations_path
        end
    end

    protected

    def set_conversation
        @conversation = Conversation.find(params[:id])
    end

    def conversation_params
        params.require(:conversation).permit(:receiver_id)
    end

    def check_if_exists
        @conversation = Conversation.between(current_user, User.find(params[:conversation][:receiver_id])).first
        if @conversation
            @personal_message = PersonalMessage.new
            render "show", conversation: @conversation, personal_message: @personal_message
        end
    end

    def mark_as_read(messages)
        messages.update_all(read_at: Time.now)
    end

    def destroy_if_empty
        @conversation.destroy if @conversation.personal_messages.empty?
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
    def participating_user(conversation)
        current_user == conversation.author ? conversation.receiver : conversation.author
    end

    def messages_count
        count = 0
        conversations = Conversation.participates(current_user)
        conversations.each do |conversation|
            count += conversation.personal_messages.unread(current_user).count
        end
        count
    end
end

app/views/conversations/_conversation.haml
- if conversation.personal_messages.any?
    %li.conversation.list-group-item
        = link_to conversation_path(conversation), remote: true do
            - user = participating_user(conversation)
            .header
                .user-avatar
                    = image_tag user.avatar
                .username    
                    %p
                        = user.name
                        %small= "@#{ user.username }"
            .message
                = "#{ conversation.personal_messages.last.user == user ? user.name : 'You' }:"
                %small= conversation.personal_messages.last.body
            - if conversation.personal_messages.unread(current_user).any?    
                .pull-right
                    %span.unread-messages-count
                        = messages_count

app/views/conversations/_dialog_messages.haml
#modal-messages.modal{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5.modal-title Personal messages
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        
      .modal-footer

app/views/conversations/_index.haml
%ul.list-group-flush
    = render @conversations

app/views/conversations/_new.haml
.new-conversation.top-space
    .search_user
        = form_with(model:conversation) do |f|
            .form-group
                = f.hidden_field "receiver_id", id: "conversation_receiver_id"
                = text_field_tag "to", nil, placeholder: "enter a name", autocomplete: "off", class: "form-control", autofocus: true, require: true
            .form-group
                = f.submit "Next", class: "btn btn-primary"
    %ul.people.list-group-flush
        %h4 Recent users
        - current_user.authored_conversations.last(3).each do |conver|
            = render "conversations/user", user: conver.receiver

app/views/conversations/_personal_message.haml
.PM_container{ id: "pm_#{ personal_message.id }" }
    %div{ class: "#{ personal_message.user == current_user ? 'right' : 'left' }" }
        %p= personal_message.body

app/views/conversations/_show.haml
.PM_conversation.top-space
    - user = participating_user(conversation)
    .header
        = link_to conversations_path, remote: true, class: "back-btn" do
            %i.fa.fa-angle-left
        = link_to profile_user_path(user) do
            .user-avatar
                = image_tag user.avatar
            .username
                %p= user.name
        .action
            = link_to conversation_path(conversation), method: :delete, data: { confirm: "Are you sure?" } do
                %i.fa.fa-trash
    .PM_conversation_container{ "data-conversation-id": conversation.id }
        = render partial: "personal_message", collection: conversation.personal_messages, as: :personal_message || "There are no messages."
.PM_composer
    = form_for [conversation, personal_message] do |f|

        .form-group
            = f.hidden_field "conversation_id", value: conversation.id
            = f.text_area :body, class: "form-control", rows: 1, required: true
        .form-group
            .pull-right
                = f.submit "send", id: "send_message", class: "btn btn-primary"

app/views/conversations/_user.haml
%li.user.list-group-item{ data: { username: user.username, "user-id" => user.id } }
    .user-avatar
        = image_tag user.avatar
    .username
        %strong= user.name
        %small= user.username

app/views/conversations/create.js.erb
$(".modal-header").html("</a><button aria-label='Close' class='close' data-dismiss='modal' type='button'><span aria-hidden='true'>×</span></button>");
$(".modal-body").css("padding",0);
$(".modal-body .PM_conversation").css("border-top", 0);
$(".modal-body").html("<%= j render 'show', conversation: @conversation, personal_message: @personal_message %>");
$(".modal-body .PM_conversation").removeClass("top-space");
$(".modal").modal("show");

app/views/conversations/index.haml
.conversations.top-space
    .header
        %h4 Personal Messages
        .action
            = link_to new_conversation_path, class: "btn btn-primary", remote: true do
                New message
                %i.fa.fa-comment
    = render "index"
    

app/views/conversations/index.js.erb
$(".modal-header").html("<div class='header'><h4>Personal Messages</h4><div class='action'><a class='btn btn-primary' href='/conversations/new' data-remote='true'>New message<i class='fa fa-comment'></i></a><button aria-label='Close' class='close' data-dismiss='modal' type='button'><span aria-hidden='true'>×</span></button></div></div>");
$(".modal-body").html("<%= j render 'index' %>");
$(".modal").modal("show");

app/views/conversations/new.haml
= render "new", conversation: @conversation

app/views/conversations/new.js.erb
$(".modal-header").html("<a class='' data-remote='true' href='/conversations'><i class='fa fa-angle-left'></i></a>");
$(".modal-header").append("<button aria-label='Close' class='close' data-dismiss='modal' type='button'><span aria-hidden='true'>×</span></button>");
$(".modal-body").css("padding",0);
$(".modal-body").html("<%= j render 'new', conversation: @conversation %>");
$(".modal-body .new_conversation").removeClass("top-space");
$(".modal").modal("show");

app/views/conversations/show.haml
= render "show", conversation: @conversation, personal_message: @personal_message

app/views/conversations/show.js.erb
$(".modal-header").html("</a><button aria-label='Close' class='close' data-dismiss='modal' type='button'><span aria-hidden='true'>×</span></button>");
$(".modal-body").css("padding",0);
$(".modal-body .PM_conversation").css("border-top", 0);
$(".modal-body").html("<%= j render 'show', conversation: @conversation, personal_message: @personal_message %>");
$(".modal-body .PM_conversation").removeClass("top-space");
$(".modal").modal("show");
$("#messages-counter").html("<%= messages_count %>")