config/routes.rb
Rails.application.routes.draw do
  
  authenticated :user do
    root to: "tweets#index", as: :authenticated_root
  end
  unauthenticated do
    root to: "main#index"
  end
  devise_for :users
  resources :users, only: [:index]
  devise_scope :user do
    post "/users/pre_register", to: "registrations#preRegister", as: :pre_registration
  end
  
  resources :tweets
  resources :conversations do
    resources :personal_messages, only: [:create]
  end
  
  put "/tweets/:id/like", to: "tweets#like", as: :like_tweet
  put "/tweets/:id/dislike", to: "tweets#dislike", as: :dislike_tweet
  
  get "/tweets/:parent_id/reply", to: "tweets#new", as: :reply_tweet
  get "/tweets/:parent_id/reply", to: "tweets#create"
  get "/tweets/:src_tweet/retweet", to: "tweets#new", as: :new_retweet
  post "/tweets/:src_tweet/retweet", to: "tweets#retweet", as: :retweet
  delete "/tweets/:id/retweet", to: "tweets#destroy_retweet", as: :destroy_retweet 
  post '/users/:username/follow_user', to: "relationships#follow_user", as: :follow_user
  post '/users/:username/unfollow_user', to: "relationships#unfollow_user", as: :unfollow_user
  
  get "/notifications", to: "notifications#index", as: :notification

  get "/search", to: "main#search", as: :search

  mount ActionCable.server => "/cable"

  get "/users/:username", to: "profiles#show", as: :profile_user, constraint: { username: /[\w]+/ }
  get "/users/:username/following", to: "profiles#following", as: :user_following, constraint: { username: /[\w]+/ }
  get "/users/:username/followers", to: "profiles#followers", as: :user_followers, constraint: { username: /[\w]+/ }

end

app/models/tweet.rb
class Tweet < ApplicationRecord
	after_save :notify_mentioned_users
	after_commit { TweetBroadcastJob.perform_later(self) }
	
	searchkick text_start: [:body]
	belongs_to :user
	belongs_to :parent, class_name: "Tweet", optional: true
	has_many :replies, foreign_key: :parent_id, class_name: "Tweet"
	belongs_to :src_tweet, class_name: "Tweet", optional: true
	has_many :retweets, foreign_key: :src_tweet_id, class_name: "Tweet"
	acts_as_votable
	validates :body, presence: true, length: { maximum: 140 }

	scope :of_followed_users, -> (user) {where(user_id: user.id).or(Tweet.where(user_id: user.following)) }
	
	def get_src_tweet
		Tweet.find(self.src_tweet.id)	
	end

	def has_src_tweet?
		self.src_tweet != nil
	end

	def mentions
		@mentions ||= begin
                    regex = /@([\w]+)/
                    matches = body.scan(regex).flatten
					        end
		
	end

	def mentioned_users
    @mentioned_users ||= User.where(username: mentions)
	end

	protected

	def notify_mentioned_users
		mentioned_users.each do |mentioned_user|
			Notification.send_notification(mentioned_user, user, "mentioned", self)
		end
	end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :set_tweet, only: [:edit, :update, :show, :destroy, :like, :dislike, :reply, :destroy_retweet]
  before_action :authenticate_user!, except: [:show]
  
  include TweetsHelper
  
  def index
    @tweets = Tweet.of_followed_users(current_user).order("created_at DESC")
    @tweet = Tweet.new
    @notifications_count = notifications_count
    @messages_count = messages_count
  end

  def new
    @tweet = Tweet.new
    if params[:src_tweet]
      @src_tweet = Tweet.find(params[:src_tweet])
    elsif params[:parent_id]
      @parent = Tweet.find(params[:parent_id])
    end
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
    @tweet.parent = Tweet.find(params[:parent]) unless params[:parent].nil?
    respond_to do |format|
      if @tweet.save 
        Notification.send_notification(@tweet.parent.user, current_user, "reply", @tweet) if @tweet.parent && @tweet.parent.user != current_user
        format.json { head :no_content }
        format.js { flash.now[:success] = "Your tweet has been created." }
        format.html { redirect_to tweets_url, notice: "Your tweet has been created." }
      else
        format.json { render json: @tweet.errors.full_messages, 
                           status: :unprocessable_entity }
        format.js { flash.now[:info] = "Your reply could not be send." }
      end
    end

  end
  
  def retweet
    @tweet = Tweet.find(params[:src_tweet])
    @retweet = current_user.tweets.new(tweet_params)
    @retweet.src_tweet = @tweet
    @retweet.body = @tweet.quote.present? ? @tweet.quote : @tweet.body
    respond_to do |format|
      if @retweet.save
        Notification.send_notification(@tweet.user, current_user, "retweet", @tweet) unless current_user == @tweet.user
        format.js
      else
        format.html { flash[:warning] = "An error has ocurred, try again." }
      end
    end
  end
  
  def destroy_retweet
    @retweet = @tweet.retweets.find_by(user: current_user)
    respond_to do |format|
      if @retweet.destroy
        Notification.find_by(recipient: @tweet.user, actor: current_user, action: "retweet").destroy unless @tweet.user == current_user
        format.html { flash[:success] = "Your retweet has been deleted." }
        format.json { head :no_content }
        format.js
      else
        format.html { flash[:warning] = "An error has ocurred, try again." }
        format.json { render json: @tweet.errors.full_messages, 
                            status: :unprocessable_entity }
      end
    end
  end

  def show
    @tweets = @tweet.replies
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @tweet.errors.full_messages, 
                            status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def like
    if @tweet.like_by current_user
      Notification.send_notification(@tweet.user, current_user, "liked", @tweet) unless current_user == @tweet.user
      @retweet = @tweet.get_src_tweet if @tweet.has_src_tweet?
      respond_to do |format|
        format.json { head :no_content }
        format.js
      end
    end
  end

  def dislike
    if @tweet.unliked_by current_user
      Notification.find_by(recipient: @tweet.user, actor: current_user, action: "liked").destroy unless @tweet.user == current_user
      if current_user.retweet_it?(@tweet)
        @retweet = @tweet.retweets.find_by(user_id: current_user)
      end
      respond_to do |format|
        format.json { head :no_content }
        format.js
      end
    end
  end

  def destroy
    if @tweet.destroy 
      Notification.find_by(recipient: @tweet.parent.user, actor: current_user, action: "reply").destroy if @tweet.parent && @tweet.parent.user != current_user
      respond_to do |format|
        format.json { head :no_content }
        format.js
      end
    end
  end

  private
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:body, :parent, :quote, :src_tweet)
    end

    def trigger_tweet_to_followers(tweet)
      
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def own_tweet?(tweet)
       current_user == tweet.user
    end
    
    def get_src_tweet(tweet)
       @src_tweet = tweet.src_tweet
    end

    def linked_users(body)
      body.gsub /@([\w]+)/ do |match|
         link_to match, profile_user_path($1)
      end.html_safe
    end

end

app/views/tweets/_dialog.haml
.modal.fade#modal-tweet{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4.modal-title
      .modal-body

app/views/tweets/_dislike_btn.haml
= link_to dislike_tweet_path(tweet), class: "liked", method: :put, remote: true do
	.icon-container
		%i{ class: "fa fa-heart", "data-toggle" => "tooltip", "data-placement" =>"top", :title => "Dislike" }
	.text-container
		.action-count
			%span= tweet.get_likes.size

app/views/tweets/_like_btn.haml
= link_to like_tweet_path(tweet), method: :put, remote: true do
	.icon-container
		%i{ class: "fa fa-heart", "data-toggle" => "tooltip", "data-placement" =>"top", :title => "Like" }
	.text-container
		.action-count
			%span= tweet.get_likes.size

app/views/tweets/_quote_tweet.haml
.header
	.account
		= link_to profile_user_path(tweet.user) do
			.user-avatar
				= image_tag tweet.user.avatar
			.text
				.username
					%span.fullname
						%strong= tweet.user.name
					%span @#{ tweet.user.username }
	%small{ class: "time" }= time_ago_in_words(tweet.created_at)
	.dropdown
		%button#dropdownMenu1.btn.btn-action.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown"}
			%i.fa.fa-chevron-down{"data-toggle" => "tooltip", "data-placement" =>"top", :title => "More"}
		%ul.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdownMenu1"}
			%li
				%a{ href: "#" } Share
			- if tweet.user == current_user
				%li
					= link_to "Edit", edit_tweet_path(tweet), remote: true
				%li
					= link_to "Delete", tweet, method: :delete, data: { confirm: "Are you sure?" }, remote: true
			- else
				%li
					%a{ href: "#" } Report
.body
	.quote
		= tweet.quote
		.tweet.top-space.bottom-space
			.tweet-actionable{"data-url" => tweet_path(src_tweet.id) }
				.header
					.account
						= link_to profile_user_path(src_tweet.user) do
							.text
								.username
									%span.fullname
										%strong= src_tweet.user.name
									%span @#{ src_tweet.user.username }
				.body
					%p= tweet.body
= render "tweets/tweet_footer", tweet: tweet

app/views/tweets/_retweet.haml
- get_src_tweet(tweet)
- if tweet.quote.present?
	= render "tweets/quote_tweet", tweet: tweet, src_tweet: @src_tweet
- else
	.context
		%small
			Retweet 
			%i.fa.fa-retweet.text-green
			by
			- if own_tweet?(tweet)
				you
			- else
				@#{ tweet.user.username }
	= render "tweets/tweet_content", tweet: @src_tweet

app/views/tweets/_retweet_btn.haml
- if current_user.retweet_it?(tweet)
	= link_to destroy_retweet_path(tweet), class: "retweet-it", method: :delete, remote: true do
		.icon-container
			%i{ class: "fa fa-retweet", "data-toggle" => "tooltip", "data-placement" =>"top", :title => "Undo retweet" }
		.text-container
		.action-count
			%span= tweet.retweets.size
- else
	= link_to new_retweet_path(tweet), data: { :toggle => "modal", :target => "#modal-tweet", remote: true } do
		.icon-container
			%i{ class: "fa fa-retweet", "data-toggle" => "tooltip", "data-placement" =>"top", :title => "Retweet" }
		.text-container
		.action-count
			%span= tweet.retweets.size
	// = link_to retweet_path(tweet), class: "retweet", method: :post, remote: true do
	// 	.icon-container
	// 		%i{ class: "fa fa-retweet", "data-toggle" => "tooltip", "data-placement" =>"top", :title => "Retweet" }
	// 	.text-container
	// 	.action-count
	// 		%span= tweet.retweets.size

app/views/tweets/_show.haml
.container-fluid.top-space
	= render @tweet
	= render "reply_form", parent: @tweet
	.replies
		= render @tweets

app/views/tweets/_tweet_content.haml
.header
  .account
    = link_to profile_user_path(tweet.user.username) do
      .user-avatar
        = image_tag tweet.user.avatar
      .text
        .username
          %span.fullname
            %strong= tweet.user.name
          %span @#{tweet.user.username}
  %small{ class: "time" }= time_ago_in_words(tweet.created_at)
  .dropdown
    %button.btn.btn-action.dropdown-toggle{ id: "dropdownMenu#{tweet.id}", "aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown"}
      %i.fa.fa-chevron-down{"data-toggle" => "tooltip", "data-placement" =>"top", :title => "More"}
    %ul.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdownMenu#{tweet.id}"}
      %li
        %a{ href: "#" } Share
      - if tweet.user == current_user
        %li
          = link_to "Edit", edit_tweet_path(tweet), remote: true
        %li
          = link_to "Delete", tweet, method: :delete, data: { confirm: "Are you sure?" }, remote: true
      - else
        %li
          %a{ href: "#" } Report
  - if tweet.parent.present?
    .parent
      %small 
        In response to 
        = link_to "@#{ tweet.parent.user.username }", profile_user_path(tweet.parent.user)
.body
  %p= linked_users(tweet.body)
  - unless action_name == "new"
    = render "tweets/tweet_footer", tweet: tweet

app/views/tweets/edit.html.haml
.container
	%h2 Edit tweet
	= render "form"

app/views/tweets/edit.js.erb
$("#modal-tweet .modal-title").text("Edit tweet");

$(".modal-body").html("<%= j render "form" %>");

$("#modal-tweet").modal("show");

$('#modal-tweet').on('shown.bs.modal', function () {
  $('#tweet-area').focus()
})

app/views/tweets/index.html.haml
.container.top-space
  .row
    .col-sm-5.col-md-4.col-lg-3.hidden-xs
      .profile-header
        = render "profiles/profile_header", user: current_user
    .col-sm-7
      .new-tweet
        .jumbotron
          .user-avatar
            = image_tag current_user.avatar_url(:thumb), class: "img-responsive img-rounded"
          = render "form"
      %ul.tweets
        = render @tweets
        %li.tweet.text-center.bottom-space.no-more
          %i.fa.fa-twitter
          No more tweets
          %small= link_to "Back to top", "#"

app/views/tweets/reply.haml
= render "tweets/reply_form", tweet: @tweet

app/views/tweets/retweet.js.erb
$("#tweet_<%= @tweet.id %> .retweet .btn-action").html("<%= j render 'retweet_btn', tweet: @tweet %>")
                                                .children("a").addClass(".retweet-it");
$(".tweets").prepend("<%= j render "tweet", tweet: @retweet %>");
$(".modal").modal("toggle");

app/views/tweets/update.js.haml
:plain
	$("#modal-tweet").modal("toggle");
	("#tweet_#{ tweet.id }").append("#{ j render @tweet }").replaceWith("#{ j render @tweet }");