config/routes.rb
Rails.application.routes.draw do
  
  authenticated :user do
    root to: "tweets#index", as: :authenticated_root
  end
  unauthenticated do
    root to: "main#index"
  end
  devise_for :users
  resources :users, only: [:index]
  devise_scope :user do
    post "/users/pre_register", to: "registrations#preRegister", as: :pre_registration
  end
  
  resources :tweets
  resources :conversations do
    resources :personal_messages, only: [:create]
  end
  
  put "/tweets/:id/like", to: "tweets#like", as: :like_tweet
  put "/tweets/:id/dislike", to: "tweets#dislike", as: :dislike_tweet
  
  get "/tweets/:parent_id/reply", to: "tweets#new", as: :reply_tweet
  get "/tweets/:parent_id/reply", to: "tweets#create"
  get "/tweets/:src_tweet/retweet", to: "tweets#new", as: :new_retweet
  post "/tweets/:src_tweet/retweet", to: "tweets#retweet", as: :retweet
  delete "/tweets/:id/retweet", to: "tweets#destroy_retweet", as: :destroy_retweet 
  post '/users/:username/follow_user', to: "relationships#follow_user", as: :follow_user
  post '/users/:username/unfollow_user', to: "relationships#unfollow_user", as: :unfollow_user
  
  get "/notifications", to: "notifications#index", as: :notification

  get "/search", to: "main#search", as: :search

  mount ActionCable.server => "/cable"

  get "/users/:username", to: "profiles#show", as: :profile_user, constraint: { username: /[\w]+/ }
  get "/users/:username/following", to: "profiles#following", as: :user_following, constraint: { username: /[\w]+/ }
  get "/users/:username/followers", to: "profiles#followers", as: :user_followers, constraint: { username: /[\w]+/ }

end

app/views/partials/_dialog.haml
.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4.modal-title
      .modal-body

app/views/partials/_guests_nav.html.haml
%ul.nav.navbar-nav
  %li
    = link_to root_path do
      %i.fa.fa-twitter
      Home
  %li
    = link_to "#" do
      About us

%ul.nav.navbar-nav.navbar-right
  - if current_page? root_path
    = render "partials/language_nav"
  - else
    %li.dropdown
      %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => new_user_session_path, :role => "button"}
        Have an account? Sign in
        %span.caret
      %ul.dropdown-menu
        %li
          %div
            %h4 Have an account?
            = render "devise/sessions/form"
        %li.divider{:role => "separator"}
        %li
          %div
            %h4 New on twittah?
            = link_to "Sign up", new_user_registration_path, class: "btn btn-block btn-info"

app/views/partials/_language_nav.html.haml
%li
  %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
    Language
    %span.caret
  %ul.dropdown-menu
    %li
      %a{:href => "#"} English
    %li
      %a{:href => "#"} Spanish

app/views/partials/_members_nav.html.haml
%ul.nav.navbar-nav
  %li.active
    = link_to root_path do
      %i.fa.fa-home
      Home
  %li
    = link_to notification_path do
      %i.fa.fa-bell
      Notifications
      %small#notification-counter.pull-right
        = @notifications_count
  %li
    = link_to conversations_path, data: { toggle: "modal", target: ".modal" }, remote: true do
      %i.fa.fa-envelope
      Messages
      %small#messages-counter.pull-right
        = messages_count

%ul.nav.navbar-nav.navbar-right
  %li
    %a.dropdown-toggle.account{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
      = image_tag current_user.avatar, class: "img-circle img-responsive"
      %span.visible-xs Cuenta
      %span.caret.visible-xs
    %ul.dropdown-menu
      %li
        = link_to profile_user_path(current_user) do
          %strong.center-block= current_user.name
          %small view profile
      %li.divider{:role => "separator"}
      %li
        = link_to "Account settings", edit_user_registration_path
      %li
        = link_to "Sign out", destroy_user_session_path, method: :delete
  %li.btn-tweet
    = link_to new_tweet_path, class: "btn btn-primary", data: { toggle: "modal", target: ".modal" }, remote: true do
      %i.fa.fa-pencil 
      Tweet

app/views/partials/_nav_form.html.haml
-# %form.navbar-form.navbar-right
-#   .form-group.has-feedback
-#     %input.form-control{:placeholder => "Search on twittah", :type => "text"}
-#     %i.fa.fa-search.form-control-feedback
= form_tag "/search", method: :get, class: "navbar-form navbar-right" do
  .form-group.has-feedback
    = text_field_tag "q", nil, class: "form-control", placeholder: "Search on twclone"
    %i.fa.fa-search.form-control-feedback
    

app/views/partials/_toast.haml
#toast
  .toast-header
    %img.rounded.user-avatar{:alt => "...", :src => ""}
    %strong.username
    %button.ml-2.mb-1.close{"aria-label" => "Close", "data-dismiss" => "toast", :type => "button"}
      %span{"aria-hidden" => "true"} ×
  .toast-body